version: "3.8"

services:
  proctorgo:
    build: .
    container_name: proctorgo
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/proctor
      - APP_PORT=8080
    depends_on:
      - mongo
    networks:
      - core_web_core_network

  mongo:
    image: mongo:latest
    container_name: proctor-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - core_web_core_network

networks:
  core_web_core_network:  # Use the existing FastAPI network
    external: true 

volumes:
  mongo_data:
