apiVersion: v1
kind: Service
metadata:
  name: campusone-webui-core-service
spec:
  selector:
    app: campusone-webui-core-app
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 80
  type: NodePort
